### ISSUE TITLE
'0 $BIS' balance displays as '0E-8 $BIS'

### ISSUE THREAD

**Issue by alias-bitsignal** [bismuthfoundation/TornadoWallet#3]
Display '0 $BIS' balance as '0 $BIS' and not as '0E-8 $BIS'.

**Comment by hclivess** [comment]
This can be fixed with **balance = "{:.8f}".format(Decimal(balance[0]))**
but I am not sure how @EggPool wants to do it, we could make changes on the node's end to return the full value so we don't have to import the whole Decimals module here. Decimals are disappearing soon anyway, so the format will change.

**Comment by EggPool** [comment]
Balance display uses a custom function, voluntarily not displaying the 8 decimals of the full Bismuth precision.
0 Seems to be a specific case to be handled apart.
I let that open as valid first issue.

**Comment by EggPool** [comment]
Fixed
